name: Development Actions

on:
  push:
    branches: ['**', '!main']

jobs:
  check-requirements-tesseract:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check requirements
      working-directory: tesseract
      run: |
        pip install safety && safety check -r requirements.txt
  check-requirements-mood-light:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check requirements
      working-directory: mood-light
      run: |
        pip install safety && safety check -r requirements.txt
  build-data-service:
    runs-on: [self-hosted, linux, ARM64]
    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: data-service
      run: |
        docker build -t test .