name: Development Actions

on:
  push:
    branches: ['**', '!main']

jobs:
  check-requirements-tesseract:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check requirements
      working-directory: .Tesseract/tesseract
      run: |
        pip install safety && safety check -r requirements.txt
  check-requirements-mood-light:
    runs-on: ubuntu-latest
    steps:
    - name: Check requirements
      working-directory: .Tesseract/mood-light
      run: |
        pip install safety && safety check -r requirements.txt
  test-tesseract:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      working-directory: .Tesseract/tesseract
      run: |
        cd tesseract
        python3 test_tesseract.py
  test-mood:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      working-directory: .Tesseract/mood-light
      run: |
        cd mood-light
        python3 test_main.py
