name: Development Actions

on:
  push:
    branches: ['**', '!main']

jobs:
  check-requirements-tesseract:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check requirements
      working-directory: tesseract
      run: |
        pip install safety && safety check -r requirements.txt
  check-requirements-mood-light:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check requirements
      working-directory: mood-light
      run: |
        pip install safety && safety check -r requirements.txt
  build-data-service:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: rubberdinghy911/data-service

    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ./data-service
        file: Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}