name: Development Actions

on:
  push:
    branches: ['**', '!main']

jobs:
  check-requirements-tesseract:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check requirements
      working-directory: tesseract
      run: |
        pip install safety && safety check -r requirements.txt
  check-requirements-mood-light:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check requirements
      working-directory: mood-light
      run: |
        pip install safety && safety check -r requirements.txt
  build-data-service:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - name: Build Data Service
      working-directory: data-service
      run: |
        docker build -t rubberdinghy911/data-service .
        docker tag rubberdinghy911/data-service rubberdinghy/data-service:latest
        docker login --username=$DOCKERHUB_USERNAME --password-stdin=$DOCKERHUB_PASSWORD
        docker push rubberdinghy911/data-service:latest