name: Production Actions

on: 
  push:
    branches:
      - '**'

jobs:
  check-requirements:
    runs-on: [self-hosted, linux, X64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Safety
      run: |
        pip install safety

    - name: Check requirements for Tesseract
      working-directory: tesseract
      run: |
        safety check -r requirements.txt

    - name: Check requirements for Mood Light
      working-directory: mood-light
      run: |
        safety check -r requirements.txt

  deploy-tesseract:
    runs-on: [self-hosted, linux, X64]
    needs: check-requirements
    if: contains(github.event.head_commit.message, '[tesseract]')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy Tesseract to network node
      run: |
        scp tesseract/tesseract.py tesseract/constants.py tesseract/requirements.txt pi@192.168.0.6:/home/pi/deploy/
        ssh pi@192.168.0.6 bash -c "pip3 install -r /home/pi/deploy/requirements.txt"

  deploy-mood:
    runs-on: [self-hosted, linux, X64]
    needs: check-requirements
    if: contains(github.event.head_commit.message, '[mood]')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy Mood Light to network node
      run: |
        scp mood-light/main.py mood-light/requirements.txt pi@192.168.0.151:/home/pi/deploy/
        ssh pi@192.168.0.151 bash -c "pip3 install -r /home/pi/deploy/requirements.txt"

  build-data-service:
    runs-on: [self-hosted, linux, X64]
    needs: check-requirements
    if: contains(github.event.head_commit.message, '[data-service]')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Data Service
      working-directory: data-service
      run: |
        cp -r . /home/pi/Documents/data-service
        cd /home/pi/Documents/data-service
        docker compose down
        docker build -t data-service .
        docker compose up -d

  build-website:
    runs-on: [self-hosted, linux, X64]
    needs: check-requirements
    if: contains(github.event.head_commit.message, '[website]')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Website
      working-directory: dashboard
      run: |
        cp -r . /home/pi/Documents/dashboard
        cd /home/pi/Documents/dashboard
        docker compose down
        docker build -t dashboard .
        docker compose up -d
