name: Production Actions

on:
  pull_request:
    types: closed
    branches: [ "main" ]

jobs:
  deploy-tesseract:
    runs-on: [self-hosted, linux, ARM64]
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to network node
      run: |
        scp tesseract/tesseract.py tesseract/constants.py tesseract/requirements.txt pi@192.168.0.6:/home/pi/deploy/
        ssh pi@192.168.0.6 bash -c "pip3 install -r /home/pi/deploy/requirements.txt"
  deploy-mood:
    runs-on: [self-hosted, linux, ARM64]
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to network node
      run: |
        scp mood-light/main.py mood-light/requirements.txt pi@192.168.0.59:/home/pi/deploy/
        ssh pi@192.168.0.59 bash -c "pip3 install -r /home/pi/deploy/requirements.txt"
  build-data-service:
    runs-on: [self-hosted, linux, ARM64]
    steps:
    - name: Build
      working-directory: data-service
      run: |
        cp -r . /home/pi/Documents/data-service
        cd /home/pi/Documents/data-service
        docker compose down
        docker compose up -d
  build-website:
    runs-on: [self-hosted, linux, ARM64]
    steps:
    - name: Build
      working-directory: dashboard
      run: |
        cp -r . /home/pi/Documents/dashboard
        cd /home/pi/Documents/dashboard
        docker compose down
        docker compose up -d