name: Python

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-requiremnts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check equirements
      run: pip install safety && safety check
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: python3 test_tesseract.py
  deploy:
    runs-on: [self-hosted, linux, ARM64]
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to network node
      run: secho 'Some Text' | ssh pi@192.168.0.6 -T "cat > /home/pi/remotefile.txt"
